"""empty message

Revision ID: debf7583c62b
Revises: 
Create Date: 2019-08-10 16:38:03.692398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debf7583c62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Integer, nullable=True),
    sa.Column('birthday', sa.Date, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.Integer, nullable=True),
    sa.Column('identify', sa.Integer, nullable=True),
    sa.Column('identify_id', sa.Integer, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('att_time', sa.Date, nullable=True),
    sa.Column('status', sa.Integer, nullable=True),
    sa.Column('stu_id', sa.Integer, nullable=True),
    sa.ForeignKeyConstraint(['stu_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorce',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('course', sa.Float, nullable=True),
    sa.Column('stu_id', sa.Integer, nullable=True),
    sa.Column('course_id', sa.Integer, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stu_cou',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer, nullable=True),
    sa.Column('course_id', sa.Integer, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer, autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Integer, nullable=True),
    sa.Column('birthday', sa.Date, nullable=True),
    sa.Column('course_id', sa.Integer, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('stu_cou')
    op.drop_table('sorce')
    op.drop_table('attendance')
    op.drop_table('user')
    op.drop_table('students')
    op.drop_table('course')
    # ### end Alembic commands ###
