# Generated by Django 2.1.1 on 2019-07-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='收件地址')),
                ('port_num', models.CharField(max_length=32, verbose_name='邮编')),
                ('rece_phone', models.CharField(max_length=32, verbose_name='收件人电话')),
                ('rece_name', models.CharField(max_length=32, verbose_name='收件人')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式')),
                ('connect_adress', models.TextField(blank=True, null=True, verbose_name='联系地址')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer'),
        ),
    ]
