# Generated by Django 2.1.1 on 2019-07-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('goods_id', models.IntegerField()),
                ('goods_price', models.FloatField()),
                ('goods_number', models.IntegerField()),
                ('goods_total', models.FloatField()),
                ('goods_picture', models.ImageField(upload_to='buyer/images')),
                ('isdelete', models.IntegerField(default=0)),
                ('store_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.Buyer')),
            ],
        ),
    ]
