# Generated by Django 2.1.1 on 2019-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='isdelete',
            field=models.BooleanField(default=False, verbose_name='是否下架'),
        ),
    ]
