# Generated by Django 2.1.1 on 2019-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_class',
            field=models.CharField(default=1, max_length=32, verbose_name='类别class'),
        ),
    ]
